import type { Metadata } from 'next';
import Link from 'next/link';
import { legalIdentity, missingLegalFacts, ENTITY_FALLBACK } from '@/lib/legal';
import styles from '../legal.module.css';

// The search privacy notice.
//
// §17 Legal requires it by name: "Publish a bot information page and a search
// privacy notice." It is a notice about *search*, not the network — the other
// Jubilee properties have their own, and rolling them together would mean this
// page describing systems it cannot speak for.
//
// ---------------------------------------------------------------------------
// Every factual claim below is one the code actually keeps, and most of them
// point at where. That is not a stylistic choice: a privacy notice is a binding
// representation, and the fastest way to make a false one is to describe the
// system somebody meant to build.
//
// The thirteen-month window in §17 was written here only after
// `engine/src/jobs/retention.js` existed to enforce it. Before that it would
// have been a promise nothing kept.
//
// What this page does NOT state, because software cannot know it: which legal
// entity publishes it, under which law, and where to write. Those are
// configuration, and the page says they are missing until they are supplied.
// ---------------------------------------------------------------------------

export const metadata: Metadata = {
  title: 'Search privacy notice',
  description: 'What JubileeSearch records when you search, how long it keeps it, and what it never does.',
};

export default function PrivacyPage() {
  const identity = legalIdentity();
  const missing = missingLegalFacts(identity);
  const entity = identity.entity ?? ENTITY_FALLBACK;

  return (
    <main className={styles.page}>
      <p className={styles.eyebrow}>JubileeSearch</p>
      <h1 className={styles.title}>Search <span>privacy notice</span></h1>

      <p className={styles.lead}>
        This describes what happens when you use JubileeSearch: what is written down,
        how long it stays, who else sees anything, and what we do not do. It covers
        search only. Other Jubilee sites keep their own records and publish their own
        notices.
      </p>

      <div className={styles.meta}>
        <span><b>Applies to</b> www.jubileesearch.com and its search API</span>
        {identity.effectiveDate && <span><b>Effective</b> {identity.effectiveDate}</span>}
        <span><b>Published by</b> {entity}</span>
      </div>

      <Section n="1" title="Searching without signing in">
        <p>
          You do not need an account, and search will never require one. When you run a
          search, the engine writes one row recording <strong>the words you searched
          for</strong>, the language it detected, which kind of query it decided this was,
          how long the search took, and the time.
        </p>
        <p>
          It also records <strong>which results it showed you and which one you
          clicked</strong>. That is how the ranking improves: a result people choose over
          the one above it should move up. It is counted across everybody together,
          never assembled into a picture of you.
        </p>
        <p>
          A short random identifier is generated by your browser and sent with each
          search so the searches in one sitting can be told apart from a different
          reader&rsquo;s. It is not linked to you, it is not a cookie, and it disappears
          when you close the tab.
        </p>
      </Section>

      <Section n="2" title="Signing in, if you choose to">
        <p>
          Signing in is optional and changes exactly one thing about what is recorded:
          your searches are stored with your <strong>Jubilee ID</strong> instead of
          anonymously. The <Link href="/signin">sign-in page</Link> says so before you
          click, because it is a cost and not a feature.
        </p>
        <p>
          We never see your password. You authenticate at the Jubilee ID service, which
          tells us who you are and what you are allowed to do. There is no separate
          account here and nothing to reset.
        </p>
      </Section>

      <Section n="3" title="What is stored, and for how long">
        <div className={styles.wrap}>
          <table className={styles.table}>
            <thead>
              <tr><th>What</th><th>Why</th><th>How long</th></tr>
            </thead>
            <tbody>
              <tr>
                <td>Your search words</td>
                <td>To return results, to find subjects the network has not written about yet, and to improve ranking</td>
                <td>Kept, but detached from any identifier after 13 months</td>
              </tr>
              <tr>
                <td>Your Jubilee ID</td>
                <td>Only recorded while you are signed in</td>
                <td><strong>Removed after 13 months</strong></td>
              </tr>
              <tr>
                <td>The per-sitting identifier</td>
                <td>To tell one reader&rsquo;s session apart from another&rsquo;s</td>
                <td><strong>Removed after 13 months</strong>; gone from your browser when you close the tab</td>
              </tr>
              <tr>
                <td>Results shown and clicked</td>
                <td>Aggregate ranking signal</td>
                <td>Kept, with nothing left connecting it to a person</td>
              </tr>
              <tr>
                <td>Your IP address, if you report a result</td>
                <td>To investigate abuse of the report form</td>
                <td><strong>Removed after 13 months.</strong> The report itself is kept as a record of the decision</td>
              </tr>
              <tr>
                <td>Your IP address, otherwise</td>
                <td>Rate limiting only</td>
                <td><strong>Held in memory for one minute and never written down</strong></td>
              </tr>
              <tr>
                <td>What you write on the <Link href="/suggest">request form</Link>, if you use it</td>
                <td>To tell the writing team what the network is missing</td>
                <td>
                  Kept. <strong>Nothing identifying is stored with it</strong> — no
                  Jubilee ID, no session, no IP — so there is nothing to detach later
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <p>
          The removal happens on a scheduled job, not on request, and it records each
          pass so the claim can be checked rather than taken on trust.
        </p>
      </Section>

      <Section n="4" title="What we do not do">
        <div className={styles.pledge}>
          <p>
            <strong>No profile of you.</strong> Nothing is built up across Jubilee sites
            or across your visits. Your results are not personalised from your history,
            and the engine has no code that could do it.
          </p>
          <p>
            <strong>No advertising, and nothing is sold.</strong> There is no paid
            placement in results and no data broker anywhere in this.
          </p>
          <p>
            <strong>No answers written about you or for you.</strong> Result summaries
            are extracts quoted from the pages themselves. The engine indexes, ranks and
            quotes; it does not compose.
          </p>
          <p>
            <strong>No images are loaded from anyone.</strong> Result cards are text
            only, at every tier, so no third-party image can watch you read a results
            page.
          </p>
        </div>
      </Section>

      <Section n="5" title="Cookies and what your browser keeps">
        <p>There are no advertising or analytics cookies. What exists is:</p>
        <ul>
          <li>
            <strong>A sign-in cookie</strong>, only if you sign in. It is encrypted, and
            marked so that no JavaScript on the page can read it.
          </li>
          <li>
            <strong>A ten-minute cookie during sign-in</strong>, which protects the
            sign-in from being tampered with in transit. It is deleted the moment you
            return.
          </li>
          <li>
            <strong>Your display preferences</strong> — whether the wider-web results are
            collapsed, whether you chose &ldquo;Jubilee only&rdquo;, whether the
            navigation rail is open. These stay in your browser and are never sent to us.
          </li>
          <li>
            <strong>A place name, only if you ask for one.</strong> The footer&rsquo;s
            location control does nothing until you press it.
          </li>
        </ul>
      </Section>

      <Section n="6" title="Who else sees anything">
        <p>Being exact about this matters more than being brief.</p>
        <ul>
          <li>
            <strong>Jubilee&rsquo;s own inference service</strong> receives the words you
            searched for, in order to work out what you meant. It is operated by{' '}
            {entity} on Jubilee hardware, not by an outside provider.
          </li>
          <li>
            <strong>The Jubilee ID service</strong> handles sign-in, if you use it, and
            therefore knows that you signed in to search.
          </li>
          <li>
            <strong>Google Fonts</strong> serves two of the typefaces on these pages,
            which means Google receives your IP address when a page loads. This is the
            one third party that sees anything without you choosing it, and it is
            avoidable — see the note below.
          </li>
          <li>
            <strong>OpenStreetMap&rsquo;s Nominatim</strong> receives your coordinates
            only if you press &ldquo;Use my location&rdquo;. Nothing is sent otherwise.
          </li>
          <li>
            <strong>Sites you click through to</strong> see that you arrived, as they
            would from any link.
          </li>
        </ul>
        <p>
          No advertising network, analytics vendor or data broker is involved in any of
          this, and none has ever been.
        </p>
      </Section>

      <Section n="7" title="Pages we index that are not ours">
        <p>
          JubileeSearch also reads other people&rsquo;s public web pages so they can be
          found. It stores extracted text to build the index and to show a short quotation
          beside a link back to the original. It obeys <code>robots.txt</code>, never
          downloads images, and identifies itself honestly — the{' '}
          <Link href="/bot">crawler page</Link> explains how to keep it out.
        </p>
        <p>
          If you publish a page and want it removed from the index, write to us and we
          will remove it within five business days. You do not need to give a reason.
        </p>
      </Section>

      <Section n="8" title="Asking us about your own records">
        <p>
          You can ask what is held against your Jubilee ID, ask for it to be removed
          early, or ask a question about anything on this page.
        </p>
        {identity.contact ? (
          <p><a href={`mailto:${identity.contact}`}>{identity.contact}</a></p>
        ) : (
          <p>
            The contact address for these requests has not been published yet. See the
            note at the end of this page.
          </p>
        )}
        <p>
          Signing out stops new searches being recorded against your Jubilee ID
          immediately. It does not delete what is already recorded; ask us for that.
        </p>
      </Section>

      <Section n="9" title="Changes">
        <p>
          If what the engine records changes, this page changes with it, and the change
          is made here before the behaviour ships rather than after. Where the difference
          is material we will say so plainly rather than quietly reissuing the page.
        </p>
      </Section>

      {missing.length > 0 && (
        <div className={styles.todo}>
          <b>This notice is not finished, and must not be published as it stands.</b>
          Everything above about what the software does is accurate and verifiable
          against the code. What is missing is the part software cannot know, and it has
          been left blank rather than invented:
          <ul>
            {missing.map((m) => (
              <li key={m.key}><code>{m.key}</code> &mdash; {m.what}</li>
            ))}
          </ul>
          It also has not been reviewed by anyone qualified to review it. A privacy
          notice is a binding statement to readers and regulators; this one is written
          from the implementation and needs a lawyer&rsquo;s eyes before it is relied on.
        </div>
      )}

      <nav className={styles.footerNav}>
        <Link href="/">Search</Link>
        <Link href="/terms">Terms of use</Link>
        <Link href="/bot">About the crawler</Link>
        <Link href="/signin">Sign in</Link>
      </nav>
    </main>
  );
}

function Section({ n, title, children }: { n: string; title: string; children: React.ReactNode }) {
  return (
    <section className={styles.section}>
      <h2 id={`s${n}`}><em>{n}</em>{title}</h2>
      {children}
    </section>
  );
}
