-- 023 — STARTER lexicon (R2, §13.3).
--
-- ---------------------------------------------------------------------------
-- THIS DOES NOT DISCHARGE DECISION D9.
--
-- §20 D9 makes seed-lexicon authorship blocking on Phase 3 and assigns it to
-- Gabriel or a delegate, because it "is the single highest-value artifact only
-- Jubilee can produce, and search quality on your own content depends on it
-- directly." A developer cannot author Jubilee's register: the choice between
-- Yahuah, Yahweh and the LORD on a given property is an editorial and doctrinal
-- one, not a technical one.
--
-- What this file is: 46 concepts covering the four categories §13.3 lists, so
-- that the expansion path is exercised end to end and acceptance criterion 8
-- can be tested before D9 lands. Treat every row as a placeholder awaiting
-- editorial review in admin screen 3. The Romanian rows are the weakest, and
-- the Hindi rows thinner still -- both want a native speaker from the network
-- team before Phase 3 sign-off.
--
-- Terms are stored lowercase and unaccented, matching how the query normaliser
-- (§13.1 step 1) presents them for lookup. `register` is an internal label and
-- never leaves the admin console (§7.5).
-- ---------------------------------------------------------------------------

WITH concept_data(concept_key, gloss) AS (VALUES
    -- Divine names and titles
    ('yahuah',        'The divine Name. Rendered LORD in most English translations.'),
    ('yeshua',        'Jesus, by His Hebrew name.'),
    ('elohim',        'God, the Creator.'),
    ('ruach_hakodesh','The Holy Spirit.'),
    ('hamashiach',    'The Messiah, the Christ, the Anointed One.'),
    ('adonai',        'Lord, Master, as a title of address.'),
    ('abba',          'Father, in the intimate address.'),
    ('el_shaddai',    'God Almighty.'),
    -- Core Hebraic concepts
    ('teshuvah',      'Repentance, understood as turning and returning.'),
    ('chesed',        'Covenant lovingkindness, steadfast mercy.'),
    ('shalom',        'Peace, wholeness, completeness.'),
    ('mishpachah',    'Family, household, the community of belonging.'),
    ('torah',         'Instruction, teaching; also the five books.'),
    ('mitzvot',       'Commandments.'),
    ('kadosh',        'Holy, set apart.'),
    ('emunah',        'Faith, faithfulness, steadfastness.'),
    ('tzedakah',      'Righteousness expressed as charity and just dealing.'),
    ('brit',          'Covenant.'),
    ('geulah',        'Redemption, deliverance.'),
    ('tefillah',      'Prayer.'),
    ('nefesh',        'Soul, the living being.'),
    ('halakhah',      'Walk, the way one goes; practice.'),
    ('talmid',        'Disciple, one who learns by following.'),
    ('kavanah',       'Intention, the heart directed in worship.'),
    ('simcha',        'Joy, gladness.'),
    ('avodah',        'Service, work, and worship as one word.'),
    ('yetzer_hara',   'The inclination toward evil.'),
    ('olam_haba',     'The world to come.'),
    -- Appointed times
    ('shabbat',       'The seventh-day Sabbath.'),
    ('pesach',        'Passover.'),
    ('matzot',        'Unleavened Bread.'),
    ('bikkurim',      'Firstfruits.'),
    ('shavuot',       'Weeks; Pentecost.'),
    ('yom_teruah',    'Day of Trumpets; Rosh Hashanah.'),
    ('yom_kippur',    'Day of Atonement.'),
    ('sukkot',        'Tabernacles; Booths.'),
    ('hanukkah',      'Dedication; Feast of Lights.'),
    ('purim',         'Purim.'),
    -- High-traffic English concepts carrying Romanian and Hindi pairs
    ('salvation',     'Salvation, being saved, deliverance.'),
    ('forgiveness',   'Forgiveness of sins.'),
    ('worship',       'Worship, adoration.'),
    ('scripture',     'The Scriptures, the Bible.'),
    ('grace',         'Grace, unmerited favour.'),
    ('baptism',       'Baptism, immersion, mikveh.'),
    ('resurrection',  'Resurrection, rising from the dead.'),
    ('kingdom',       'The kingdom of God; the kingdom of heaven.')
)
INSERT INTO lexicon_concepts (concept_key, gloss, notes)
SELECT concept_key, gloss,
       'Starter seed, migration 023. Placeholder pending editorial authorship (decision D9).'
FROM concept_data
ON CONFLICT (concept_key) DO NOTHING;

WITH term_data(concept_key, term, lang, register, weight, is_primary) AS (VALUES
    ('yahuah','yahuah','en','OHI',1.00,true),
    ('yahuah','yahweh','en','OHI',0.90,false),
    ('yahuah','yhwh','en','OHI',0.80,false),
    ('yahuah','the lord','en','CCI',0.70,false),
    ('yahuah','jehovah','en','CCI',0.60,false),
    ('yahuah','domnul','ro','CCI',0.70,false),
    ('yeshua','yeshua','en','OHI',1.00,true),
    ('yeshua','jesus','en','CCI',1.00,false),
    ('yeshua','yahushua','en','OHI',0.80,false),
    ('yeshua','isus','ro','CCI',1.00,false),
    ('yeshua','iisus','ro','CCI',0.80,false),
    ('yeshua','yeshu','hi','common',0.70,false),
    ('elohim','elohim','en','OHI',1.00,true),
    ('elohim','god','en','CCI',1.00,false),
    ('elohim','dumnezeu','ro','CCI',1.00,false),
    ('elohim','parmeshwar','hi','common',0.80,false),
    ('ruach_hakodesh','ruach hakodesh','en','OHI',1.00,true),
    ('ruach_hakodesh','ruach ha-kodesh','en','OHI',0.95,false),
    ('ruach_hakodesh','ruach kodesh','en','OHI',0.95,false),
    ('ruach_hakodesh','holy spirit','en','CCI',1.00,false),
    ('ruach_hakodesh','holy ghost','en','CCI',0.80,false),
    ('ruach_hakodesh','duhul sfant','ro','CCI',1.00,false),
    ('ruach_hakodesh','pavitra atma','hi','common',0.80,false),
    ('hamashiach','hamashiach','en','OHI',1.00,true),
    ('hamashiach','mashiach','en','OHI',0.95,false),
    ('hamashiach','messiah','en','CCI',1.00,false),
    ('hamashiach','christ','en','CCI',1.00,false),
    ('hamashiach','mesia','ro','CCI',1.00,false),
    ('hamashiach','hristos','ro','CCI',0.90,false),
    ('adonai','adonai','en','OHI',1.00,true),
    ('adonai','lord','en','CCI',0.80,false),
    ('adonai','master','en','common',0.50,false),
    ('abba','abba','en','OHI',1.00,true),
    ('abba','father','en','CCI',0.80,false),
    ('abba','tata','ro','CCI',0.80,false),
    ('el_shaddai','el shaddai','en','OHI',1.00,true),
    ('el_shaddai','god almighty','en','CCI',1.00,false),
    ('el_shaddai','almighty','en','CCI',0.70,false),
    ('teshuvah','teshuvah','en','OHI',1.00,true),
    ('teshuvah','repentance','en','CCI',1.00,false),
    ('teshuvah','repent','en','CCI',0.90,false),
    ('teshuvah','turning back','en','common',0.70,false),
    ('teshuvah','pocainta','ro','CCI',1.00,false),
    ('chesed','chesed','en','OHI',1.00,true),
    ('chesed','hesed','en','OHI',0.95,false),
    ('chesed','lovingkindness','en','CCI',1.00,false),
    ('chesed','steadfast love','en','CCI',0.90,false),
    ('chesed','mercy','en','CCI',0.80,false),
    ('chesed','indurare','ro','CCI',0.90,false),
    ('shalom','shalom','en','OHI',1.00,true),
    ('shalom','peace','en','CCI',1.00,false),
    ('shalom','wholeness','en','common',0.70,false),
    ('shalom','pace','ro','CCI',1.00,false),
    ('shalom','shanti','hi','common',0.90,false),
    ('mishpachah','mishpachah','en','OHI',1.00,true),
    ('mishpachah','mishpacha','en','OHI',0.95,false),
    ('mishpachah','family','en','CCI',1.00,false),
    ('mishpachah','household','en','common',0.70,false),
    ('mishpachah','familie','ro','CCI',1.00,false),
    ('torah','torah','en','OHI',1.00,true),
    ('torah','instruction','en','CCI',0.80,false),
    ('torah','the law','en','CCI',0.80,false),
    ('torah','pentateuch','en','CCI',0.70,false),
    ('torah','lege','ro','CCI',0.70,false),
    ('mitzvot','mitzvot','en','OHI',1.00,true),
    ('mitzvot','mitzvah','en','OHI',0.95,false),
    ('mitzvot','commandments','en','CCI',1.00,false),
    ('mitzvot','porunci','ro','CCI',1.00,false),
    ('kadosh','kadosh','en','OHI',1.00,true),
    ('kadosh','holy','en','CCI',1.00,false),
    ('kadosh','set apart','en','OHI',0.90,false),
    ('kadosh','sanctified','en','CCI',0.80,false),
    ('kadosh','sfant','ro','CCI',1.00,false),
    ('emunah','emunah','en','OHI',1.00,true),
    ('emunah','faith','en','CCI',1.00,false),
    ('emunah','faithfulness','en','CCI',0.90,false),
    ('emunah','credinta','ro','CCI',1.00,false),
    ('emunah','vishwas','hi','common',0.80,false),
    ('tzedakah','tzedakah','en','OHI',1.00,true),
    ('tzedakah','righteousness','en','CCI',0.90,false),
    ('tzedakah','charity','en','CCI',0.70,false),
    ('brit','brit','en','OHI',1.00,true),
    ('brit','bris','en','OHI',0.70,false),
    ('brit','covenant','en','CCI',1.00,false),
    ('brit','legamant','ro','CCI',1.00,false),
    ('geulah','geulah','en','OHI',1.00,true),
    ('geulah','redemption','en','CCI',1.00,false),
    ('geulah','deliverance','en','CCI',0.90,false),
    ('geulah','rascumparare','ro','CCI',0.90,false),
    ('tefillah','tefillah','en','OHI',1.00,true),
    ('tefillah','prayer','en','CCI',1.00,false),
    ('tefillah','rugaciune','ro','CCI',1.00,false),
    ('tefillah','prarthana','hi','common',0.80,false),
    ('nefesh','nefesh','en','OHI',1.00,true),
    ('nefesh','soul','en','CCI',1.00,false),
    ('nefesh','suflet','ro','CCI',1.00,false),
    ('halakhah','halakhah','en','OHI',1.00,true),
    ('halakhah','halacha','en','OHI',0.90,false),
    ('halakhah','walk','en','common',0.50,false),
    ('talmid','talmid','en','OHI',1.00,true),
    ('talmid','talmidim','en','OHI',0.95,false),
    ('talmid','disciple','en','CCI',1.00,false),
    ('talmid','ucenic','ro','CCI',1.00,false),
    ('kavanah','kavanah','en','OHI',1.00,true),
    ('kavanah','intention','en','common',0.70,false),
    ('simcha','simcha','en','OHI',1.00,true),
    ('simcha','joy','en','CCI',1.00,false),
    ('simcha','bucurie','ro','CCI',1.00,false),
    ('avodah','avodah','en','OHI',1.00,true),
    ('avodah','service','en','common',0.60,false),
    ('yetzer_hara','yetzer hara','en','OHI',1.00,true),
    ('yetzer_hara','evil inclination','en','CCI',1.00,false),
    ('yetzer_hara','sinful nature','en','CCI',0.70,false),
    ('olam_haba','olam haba','en','OHI',1.00,true),
    ('olam_haba','world to come','en','CCI',1.00,false),
    ('olam_haba','age to come','en','CCI',0.90,false),
    ('shabbat','shabbat','en','OHI',1.00,true),
    ('shabbat','shabbos','en','OHI',0.80,false),
    ('shabbat','sabbath','en','CCI',1.00,false),
    ('shabbat','sabat','ro','CCI',1.00,false),
    ('pesach','pesach','en','OHI',1.00,true),
    ('pesach','passover','en','CCI',1.00,false),
    ('pesach','pastele','ro','CCI',0.90,false),
    ('pesach','pasti','ro','CCI',0.80,false),
    ('matzot','chag hamatzot','en','OHI',1.00,true),
    ('matzot','matzot','en','OHI',0.95,false),
    ('matzot','unleavened bread','en','CCI',1.00,false),
    ('bikkurim','bikkurim','en','OHI',1.00,true),
    ('bikkurim','yom habikkurim','en','OHI',0.95,false),
    ('bikkurim','firstfruits','en','CCI',1.00,false),
    ('shavuot','shavuot','en','OHI',1.00,true),
    ('shavuot','shavuos','en','OHI',0.80,false),
    ('shavuot','pentecost','en','CCI',1.00,false),
    ('shavuot','feast of weeks','en','CCI',0.90,false),
    ('shavuot','cincizecimea','ro','CCI',1.00,false),
    ('yom_teruah','yom teruah','en','OHI',1.00,true),
    ('yom_teruah','rosh hashanah','en','OHI',0.90,false),
    ('yom_teruah','feast of trumpets','en','CCI',1.00,false),
    ('yom_kippur','yom kippur','en','OHI',1.00,true),
    ('yom_kippur','day of atonement','en','CCI',1.00,false),
    ('yom_kippur','ziua ispasirii','ro','CCI',0.90,false),
    ('sukkot','sukkot','en','OHI',1.00,true),
    ('sukkot','succot','en','OHI',0.80,false),
    ('sukkot','tabernacles','en','CCI',1.00,false),
    ('sukkot','booths','en','CCI',0.90,false),
    ('sukkot','corturi','ro','CCI',0.90,false),
    ('hanukkah','hanukkah','en','OHI',1.00,true),
    ('hanukkah','chanukah','en','OHI',0.95,false),
    ('hanukkah','feast of dedication','en','CCI',1.00,false),
    ('purim','purim','en','OHI',1.00,true),
    ('salvation','salvation','en','CCI',1.00,true),
    ('salvation','yeshuah','en','OHI',0.90,false),
    ('salvation','saved','en','CCI',0.80,false),
    ('salvation','mantuire','ro','CCI',1.00,false),
    ('salvation','uddhar','hi','common',0.80,false),
    ('forgiveness','forgiveness','en','CCI',1.00,true),
    ('forgiveness','selichah','en','OHI',0.90,false),
    ('forgiveness','iertare','ro','CCI',1.00,false),
    ('forgiveness','kshama','hi','common',0.80,false),
    ('worship','worship','en','CCI',1.00,true),
    ('worship','hishtachavah','en','OHI',0.80,false),
    ('worship','inchinare','ro','CCI',1.00,false),
    ('worship','aradhana','hi','common',0.80,false),
    ('scripture','scripture','en','CCI',1.00,true),
    ('scripture','scriptures','en','CCI',1.00,false),
    ('scripture','the bible','en','CCI',1.00,false),
    ('scripture','tanakh','en','OHI',0.90,false),
    ('scripture','biblia','ro','CCI',1.00,false),
    ('scripture','pavitra shastra','hi','common',0.80,false),
    ('grace','grace','en','CCI',1.00,true),
    ('grace','chen','en','OHI',0.85,false),
    ('grace','favour','en','CCI',0.80,false),
    ('grace','har','ro','CCI',1.00,false),
    ('baptism','baptism','en','CCI',1.00,true),
    ('baptism','immersion','en','CCI',0.90,false),
    ('baptism','mikveh','en','OHI',0.90,false),
    ('baptism','botez','ro','CCI',1.00,false),
    ('resurrection','resurrection','en','CCI',1.00,true),
    ('resurrection','techiyat hametim','en','OHI',0.85,false),
    ('resurrection','risen','en','CCI',0.70,false),
    ('resurrection','inviere','ro','CCI',1.00,false),
    ('kingdom','kingdom of god','en','CCI',1.00,true),
    ('kingdom','kingdom of heaven','en','CCI',1.00,false),
    ('kingdom','malchut','en','OHI',0.90,false),
    ('kingdom','imparatia lui dumnezeu','ro','CCI',1.00,false)
)
INSERT INTO lexicon_terms (concept_id, term, lang, register, weight, is_primary)
SELECT c.id, t.term, t.lang, t.register, t.weight, t.is_primary
FROM term_data t
JOIN lexicon_concepts c ON c.concept_key = t.concept_key
ON CONFLICT (term, lang, concept_id) DO NOTHING;
