-- 037 — Romanian terms for every seed concept (D9, acceptance 9).
--
-- The seed (023) carried 36 Romanian terms, one word each, and thirteen
-- concepts had none. Two Romanian sites are now in the index (pocaieste.com,
-- pocaintasibotez.com, §OPEN-ITEMS 15) and the cross-language pairs resolve
-- only through the lexicon, so the Romanian side has to speak the way the
-- prose does: the definite article is a suffix (legământ / legământul), the
-- genitive changes the ending (pocăință / pocăinței), and the everyday word is
-- often not the theological one (Duhul Sfânt, but readers also write duhul).
--
-- Every term is lowercase and unaccented, as `text/normalize.js` leaves a
-- query. Weights follow 023: the primary rendering 1.00, an inflection 0.90,
-- a looser synonym 0.70-0.80. Register CCI is the common-church rendering;
-- OHI marks a transliterated Hebrew form kept in Romanian usage.
-- Nothing here touches English terms, and re-running is a no-op.

WITH term_data(concept_key, term, lang, register, weight, is_primary) AS (VALUES
    -- concepts that had no Romanian at all
    ('adonai','domnul','ro','CCI',0.80,false),
    ('adonai','stapanul','ro','CCI',0.80,false),
    ('adonai','stapane','ro','CCI',0.70,false),
    ('avodah','slujire','ro','CCI',1.00,false),
    ('avodah','slujirea','ro','CCI',0.90,false),
    ('avodah','slujba','ro','CCI',0.80,false),
    ('bikkurim','primele roade','ro','CCI',1.00,false),
    ('bikkurim','parga','ro','CCI',0.90,false),
    ('el_shaddai','cel atotputernic','ro','CCI',1.00,false),
    ('el_shaddai','dumnezeul atotputernic','ro','CCI',0.95,false),
    ('el_shaddai','atotputernic','ro','CCI',0.80,false),
    ('halakhah','umblare','ro','CCI',1.00,false),
    ('halakhah','umblarea','ro','CCI',0.90,false),
    ('halakhah','umblarea noua','ro','CCI',0.90,false),
    ('hanukkah','hanuca','ro','OHI',1.00,false),
    ('hanukkah','sarbatoarea luminilor','ro','CCI',0.90,false),
    ('kavanah','intentie','ro','CCI',0.90,false),
    ('kavanah','inima indreptata','ro','CCI',0.80,false),
    ('matzot','azime','ro','CCI',1.00,false),
    ('matzot','azimele','ro','CCI',0.90,false),
    ('matzot','painea nedospita','ro','CCI',0.90,false),
    ('olam_haba','lumea viitoare','ro','CCI',1.00,false),
    ('olam_haba','veacul viitor','ro','CCI',0.90,false),
    ('olam_haba','viata vesnica','ro','CCI',0.70,false),
    ('purim','purim','ro','OHI',1.00,false),
    ('tzedakah','dreptate','ro','CCI',1.00,false),
    ('tzedakah','milostenie','ro','CCI',0.90,false),
    ('tzedakah','neprihanire','ro','CCI',0.90,false),
    ('yetzer_hara','firea pamanteasca','ro','CCI',1.00,false),
    ('yetzer_hara','inclinatia spre rau','ro','CCI',0.90,false),
    ('yetzer_hara','firea veche','ro','CCI',0.80,false),
    ('yom_teruah','ziua trambitelor','ro','CCI',1.00,false),
    ('yom_teruah','sarbatoarea trambitelor','ro','CCI',0.95,false),
    ('yom_teruah','rosh hashana','ro','OHI',0.80,false),

    -- inflections and everyday forms for concepts that had one word
    ('abba','tatal','ro','CCI',0.90,false),
    ('abba','tata ceresc','ro','CCI',0.90,false),
    ('baptism','botezul','ro','CCI',0.90,false),
    ('baptism','scufundare','ro','CCI',0.70,false),
    ('baptism','apa','ro','CCI',0.60,false),
    ('brit','legamantul','ro','CCI',0.90,false),
    ('brit','legamant','ro','CCI',1.00,false),
    ('chesed','bunatate','ro','CCI',0.90,false),
    ('chesed','bunatatea','ro','CCI',0.80,false),
    ('chesed','mila','ro','CCI',0.80,false),
    ('chesed','indurarea','ro','CCI',0.90,false),
    ('chesed','bunatate statornica','ro','CCI',1.00,false),
    ('elohim','dumnezeul','ro','CCI',0.90,false),
    ('emunah','credinta','ro','CCI',1.00,false),
    ('emunah','credinciosie','ro','CCI',0.90,false),
    ('emunah','statornicie','ro','CCI',0.80,false),
    ('forgiveness','iertarea','ro','CCI',0.90,false),
    ('forgiveness','iertarea pacatelor','ro','CCI',0.95,false),
    ('forgiveness','a ierta','ro','CCI',0.80,false),
    ('geulah','rascumpararea','ro','CCI',0.90,false),
    ('geulah','izbavire','ro','CCI',0.90,false),
    ('geulah','eliberare','ro','CCI',0.80,false),
    ('grace','harul','ro','CCI',0.90,false),
    ('grace','harul lui dumnezeu','ro','CCI',0.95,false),
    ('hamashiach','unsul','ro','CCI',0.80,false),
    ('hamashiach','hristosul','ro','CCI',0.80,false),
    ('kadosh','sfintenie','ro','CCI',0.90,false),
    ('kadosh','pus deoparte','ro','CCI',0.90,false),
    ('kadosh','consacrare','ro','CCI',0.85,false),
    ('kadosh','sfintit','ro','CCI',0.80,false),
    ('kingdom','imparatia','ro','CCI',0.90,false),
    ('kingdom','imparatia cerurilor','ro','CCI',0.95,false),
    ('mishpachah','familia','ro','CCI',0.90,false),
    ('mishpachah','casa','ro','CCI',0.60,false),
    ('mitzvot','poruncile','ro','CCI',0.90,false),
    ('mitzvot','porunca','ro','CCI',0.85,false),
    ('nefesh','sufletul','ro','CCI',0.90,false),
    ('pesach','pastile','ro','CCI',0.85,false),
    ('resurrection','invierea','ro','CCI',0.90,false),
    ('resurrection','inviat','ro','CCI',0.80,false),
    ('resurrection','moartea si invierea','ro','CCI',0.80,false),
    ('ruach_hakodesh','duhul','ro','CCI',0.85,false),
    ('ruach_hakodesh','duh sfant','ro','CCI',0.95,false),
    ('ruach_hakodesh','duhul lui dumnezeu','ro','CCI',0.90,false),
    ('salvation','mantuirea','ro','CCI',0.90,false),
    ('salvation','mantuit','ro','CCI',0.80,false),
    ('salvation','salvare','ro','CCI',0.70,false),
    ('scripture','scriptura','ro','CCI',1.00,false),
    ('scripture','scripturile','ro','CCI',0.90,false),
    ('scripture','cuvantul lui dumnezeu','ro','CCI',0.85,false),
    ('shabbat','sabatul','ro','CCI',0.90,false),
    ('shabbat','ziua de odihna','ro','CCI',0.85,false),
    ('shabbat','odihna','ro','CCI',0.70,false),
    ('shalom','pacea','ro','CCI',0.90,false),
    ('shalom','shalom','ro','OHI',0.90,false),
    ('shavuot','cincizecime','ro','CCI',0.90,false),
    ('shavuot','rusalii','ro','CCI',0.85,false),
    ('simcha','bucuria','ro','CCI',0.90,false),
    ('simcha','veselie','ro','CCI',0.70,false),
    ('sukkot','sarbatoarea corturilor','ro','CCI',1.00,false),
    ('sukkot','colibe','ro','CCI',0.70,false),
    ('talmid','ucenicul','ro','CCI',0.90,false),
    ('talmid','ucenici','ro','CCI',0.90,false),
    ('talmid','ucenicie','ro','CCI',0.85,false),
    ('tefillah','rugaciunea','ro','CCI',0.90,false),
    ('tefillah','a se ruga','ro','CCI',0.80,false),
    ('teshuvah','pocainta','ro','CCI',1.00,false),
    ('teshuvah','pocaintei','ro','CCI',0.90,false),
    ('teshuvah','intoarcere','ro','CCI',0.90,false),
    ('teshuvah','intoarcerea','ro','CCI',0.90,false),
    ('teshuvah','intoarcerea la dumnezeu','ro','CCI',0.95,false),
    ('teshuvah','caire','ro','CCI',0.70,false),
    ('teshuvah','pocaieste','ro','CCI',0.85,false),
    ('teshuvah','pocaiti','ro','CCI',0.85,false),
    ('torah','legea','ro','CCI',0.90,false),
    ('torah','tora','ro','OHI',1.00,false),
    ('torah','invatatura','ro','CCI',0.80,false),
    ('worship','inchinarea','ro','CCI',0.90,false),
    ('worship','a se inchina','ro','CCI',0.80,false),
    ('yahuah','yahweh','ro','OHI',0.90,false),
    ('yahuah','iehova','ro','CCI',0.70,false),
    ('yeshua','isus hristos','ro','CCI',0.95,false),
    ('yeshua','domnul isus','ro','CCI',0.90,false),
    ('yeshua','yeshua','ro','OHI',0.90,false),
    ('yom_kippur','ziua ispasirii','ro','CCI',1.00,false),
    ('yom_kippur','ispasire','ro','CCI',0.85,false),
    ('yom_kippur','ispasirea','ro','CCI',0.85,false)
)
INSERT INTO lexicon_terms (concept_id, term, lang, register, weight, is_primary)
SELECT c.id, t.term, t.lang, t.register, t.weight, t.is_primary
FROM term_data t
JOIN lexicon_concepts c ON c.concept_key = t.concept_key
ON CONFLICT (term, lang, concept_id) DO NOTHING;
