-- 040 — Hindi terms in Devanagari (D9, acceptance 9).
--
-- The seed carried ten Hindi terms, all Latin transliterations (parmeshwar,
-- vishwas, uddhar ...). A Hindi reader types Devanagari, and `text/normalize.js`
-- keeps Devanagari intact (verified: "पवित्र आत्मा" tokenises to its two words
-- and detects as `hi`), so the terms have to be in the script the queries are
-- in. The transliterations stay for readers who type Hinglish.
--
-- No Hindi content exists in the corpus yet, so these terms bridge a Hindi
-- query to the ENGLISH page on the same concept -- which is what criterion 9
-- asks for on the query side. Renderings follow the Hindi Bible (Hindi O.V. /
-- IRV) usage: अनुग्रह for grace, वाचा for covenant, पश्चाताप for repentance,
-- मन फिराव as the common-church synonym, पवित्र आत्मा for the Holy Spirit.

WITH term_data(concept_key, term, lang, register, weight, is_primary) AS (VALUES
    ('abba','पिता','hi','CCI',0.90,false),
    ('abba','अब्बा','hi','OHI',1.00,false),
    ('adonai','प्रभु','hi','CCI',1.00,false),
    ('adonai','स्वामी','hi','CCI',0.80,false),
    ('avodah','सेवा','hi','CCI',1.00,false),
    ('avodah','सेवकाई','hi','CCI',0.90,false),
    ('baptism','बपतिस्मा','hi','CCI',1.00,false),
    ('bikkurim','पहले फल','hi','CCI',1.00,false),
    ('brit','वाचा','hi','CCI',1.00,false),
    ('brit','नियम','hi','CCI',0.70,false),
    ('chesed','करुणा','hi','CCI',0.90,false),
    ('chesed','दया','hi','CCI',0.90,false),
    ('chesed','अटल प्रेम','hi','CCI',1.00,false),
    ('el_shaddai','सर्वशक्तिमान','hi','CCI',1.00,false),
    ('el_shaddai','सर्वशक्तिमान परमेश्वर','hi','CCI',0.95,false),
    ('elohim','परमेश्वर','hi','CCI',1.00,false),
    ('elohim','ईश्वर','hi','CCI',0.80,false),
    ('emunah','विश्वास','hi','CCI',1.00,false),
    ('emunah','विश्वासयोग्यता','hi','CCI',0.90,false),
    ('forgiveness','क्षमा','hi','CCI',1.00,false),
    ('forgiveness','पापों की क्षमा','hi','CCI',0.95,false),
    ('geulah','छुटकारा','hi','CCI',1.00,false),
    ('geulah','मुक्ति','hi','CCI',0.80,false),
    ('grace','अनुग्रह','hi','CCI',1.00,false),
    ('grace','कृपा','hi','CCI',0.85,false),
    ('halakhah','चाल चलन','hi','CCI',0.90,false),
    ('hamashiach','मसीह','hi','CCI',1.00,false),
    ('hamashiach','अभिषिक्त','hi','CCI',0.80,false),
    ('hanukkah','हनुक्का','hi','OHI',1.00,false),
    ('kadosh','पवित्र','hi','CCI',1.00,false),
    ('kadosh','पवित्रता','hi','CCI',0.90,false),
    ('kadosh','अलग किया हुआ','hi','CCI',0.80,false),
    ('kavanah','मन की लगन','hi','CCI',0.80,false),
    ('kingdom','परमेश्वर का राज्य','hi','CCI',1.00,false),
    ('kingdom','स्वर्ग का राज्य','hi','CCI',0.95,false),
    ('kingdom','राज्य','hi','CCI',0.70,false),
    ('matzot','अखमीरी रोटी','hi','CCI',1.00,false),
    ('mishpachah','परिवार','hi','CCI',1.00,false),
    ('mishpachah','घराना','hi','CCI',0.85,false),
    ('mitzvot','आज्ञा','hi','CCI',1.00,false),
    ('mitzvot','आज्ञाएँ','hi','CCI',0.95,false),
    ('nefesh','आत्मा','hi','CCI',0.80,false),
    ('nefesh','प्राण','hi','CCI',1.00,false),
    ('olam_haba','आने वाला युग','hi','CCI',1.00,false),
    ('olam_haba','अनन्त जीवन','hi','CCI',0.70,false),
    ('pesach','फसह','hi','CCI',1.00,false),
    ('purim','पूरीम','hi','OHI',1.00,false),
    ('resurrection','पुनरुत्थान','hi','CCI',1.00,false),
    ('resurrection','जी उठना','hi','CCI',0.90,false),
    ('ruach_hakodesh','पवित्र आत्मा','hi','CCI',1.00,false),
    ('ruach_hakodesh','परमेश्वर का आत्मा','hi','CCI',0.85,false),
    ('salvation','उद्धार','hi','CCI',1.00,false),
    ('salvation','मुक्ति','hi','CCI',0.80,false),
    ('scripture','पवित्रशास्त्र','hi','CCI',1.00,false),
    ('scripture','बाइबल','hi','CCI',0.95,false),
    ('scripture','परमेश्वर का वचन','hi','CCI',0.85,false),
    ('shabbat','सब्त','hi','CCI',1.00,false),
    ('shabbat','विश्राम का दिन','hi','CCI',0.85,false),
    ('shalom','शांति','hi','CCI',1.00,false),
    ('shalom','शालोम','hi','OHI',0.90,false),
    ('shavuot','पिन्तेकुस्त','hi','CCI',1.00,false),
    ('shavuot','सप्ताहों का पर्व','hi','CCI',0.85,false),
    ('simcha','आनंद','hi','CCI',1.00,false),
    ('simcha','आनन्द','hi','CCI',0.95,false),
    ('sukkot','झोपड़ियों का पर्व','hi','CCI',1.00,false),
    ('talmid','चेला','hi','CCI',1.00,false),
    ('talmid','शिष्य','hi','CCI',0.95,false),
    ('tefillah','प्रार्थना','hi','CCI',1.00,false),
    ('teshuvah','पश्चाताप','hi','CCI',1.00,false),
    ('teshuvah','मन फिराव','hi','CCI',0.95,false),
    ('teshuvah','मन फिराना','hi','CCI',0.90,false),
    ('teshuvah','लौट आना','hi','CCI',0.80,false),
    ('torah','व्यवस्था','hi','CCI',1.00,false),
    ('torah','तोरा','hi','OHI',0.95,false),
    ('torah','शिक्षा','hi','CCI',0.70,false),
    ('tzedakah','धार्मिकता','hi','CCI',1.00,false),
    ('tzedakah','दान','hi','CCI',0.80,false),
    ('worship','आराधना','hi','CCI',1.00,false),
    ('worship','उपासना','hi','CCI',0.90,false),
    ('yahuah','यहोवा','hi','CCI',1.00,false),
    ('yahuah','याह्वे','hi','OHI',0.85,false),
    ('yeshua','यीशु','hi','CCI',1.00,false),
    ('yeshua','यीशु मसीह','hi','CCI',0.95,false),
    ('yeshua','येशुआ','hi','OHI',0.85,false),
    ('yetzer_hara','पापी स्वभाव','hi','CCI',1.00,false),
    ('yetzer_hara','शरीर की लालसा','hi','CCI',0.80,false),
    ('yom_kippur','प्रायश्चित का दिन','hi','CCI',1.00,false),
    ('yom_teruah','तुरहियों का पर्व','hi','CCI',1.00,false)
)
INSERT INTO lexicon_terms (concept_id, term, lang, register, weight, is_primary)
SELECT c.id, t.term, t.lang, t.register, t.weight, t.is_primary
FROM term_data t
JOIN lexicon_concepts c ON c.concept_key = t.concept_key
ON CONFLICT (term, lang, concept_id) DO NOTHING;
